[[FileDigestGroup]]
package = "pam_krb5"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_krb5.so",
    "*/security/pam_krb5afs.so",
]

[[FileDigestGroup]]
package = "ecryptfs-utils"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_ecryptfs.so",
]

[[FileDigestGroup]]
package = "gnome-keyring-pam"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_gnome_keyring.so",
]

[[FileDigestGroup]]
package = "samba-winbind"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_winbind.so",
]

[[FileDigestGroup]]
package = "pam_ssh"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_ssh.so",
]

[[FileDigestGroup]]
package = "pam_mount"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_mount.so",
]

[[FileDigestGroup]]
package = "pam_ccreds"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_ccreds.so",
]

[[FileDigestGroup]]
package = "pam_radius"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_radius_auth.so",
]

[[FileDigestGroup]]
package = "pam_pkcs11"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_pkcs11.so",
]

[[FileDigestGroup]]
package = "nss-pam-ldapd"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_ldap.so",
]

[[FileDigestGroup]]
package = "pam_passwdqc"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_passwdqc.so",
]

[[FileDigestGroup]]
package = "pam_userpass"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_userpass.so",
]

[[FileDigestGroup]]
package = "pam_apparmor"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_apparmor.so",
]

[[FileDigestGroup]]
package = "opie"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_opie.so",
]

[[FileDigestGroup]]
package = "pam"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1171564, bsc#1171563, bsc#1171562"
nodigests = [
    "*/security/pam_access.so",
    "*/security/pam_debug.so",
    "*/security/pam_deny.so",
    "*/security/pam_echo.so",
    "*/security/pam_env.so",
    "*/security/pam_exec.so",
    "*/security/pam_faildelay.so",
    "*/security/pam_filter.so",
    "*/security/pam_ftp.so",
    "*/security/pam_group.so",
    "*/security/pam_issue.so",
    "*/security/pam_keyinit.so",
    "*/security/pam_lastlog.so",
    "*/security/pam_limits.so",
    "*/security/pam_listfile.so",
    "*/security/pam_localuser.so",
    "*/security/pam_loginuid.so",
    "*/security/pam_mail.so",
    "*/security/pam_mkhomedir.so",
    "*/security/pam_motd.so",
    "*/security/pam_namespace.so",
    "*/security/pam_nologin.so",
    "*/security/pam_permit.so",
    "*/security/pam_pwhistory.so",
    "*/security/pam_rhosts.so",
    "*/security/pam_rootok.so",
    "*/security/pam_securetty.so",
    "*/security/pam_selinux.so",
    "*/security/pam_sepermit.so",
    "*/security/pam_shells.so",
    "*/security/pam_stress.so",
    "*/security/pam_succeed_if.so",
    "*/security/pam_time.so",
    "*/security/pam_timestamp.so",
    "*/security/pam_tty_audit.so",
    "*/security/pam_umask.so",
    "*/security/pam_warn.so",
    "*/security/pam_wheel.so",
    "*/security/pam_xauth.so",
    "*/security/pam_usertype.so",
    "*/security/pam_setquota.so",
    "*/security/pam_faillock.so",
]

[[FileDigestGroup]]
package = "pam-deprecated"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_cracklib.so",
    "*/security/pam_tally2.so",
]

[[FileDigestGroup]]
package = "pam_unix"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_unix.so",
    "*/security/pam_unix_acct.so",
    "*/security/pam_unix_auth.so",
    "*/security/pam_unix_passwd.so",
    "*/security/pam_unix_session.so",
]

[[FileDigestGroup]]
package = "pam_unix-nis"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_unix.so",
    "*/security/pam_unix_acct.so",
    "*/security/pam_unix_auth.so",
    "*/security/pam_unix_passwd.so",
    "*/security/pam_unix_session.so",
]

[[FileDigestGroup]]
package = "pam-extra"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_userdb.so",
]

[[FileDigestGroup]]
package = "systemd"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_systemd.so",
]

[[FileDigestGroup]]
package = "sssd"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_sss.so",
]

[[FileDigestGroup]]
package = "pam_mktemp"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_mktemp.so",
]

[[FileDigestGroup]]
package = "pam_csync"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_csync.so",
]

[[FileDigestGroup]]
package = "pam_chroot"
type = "pam"
note = "legacy: not audited"
bug = ""
nodigests = [
    "*/security/pam_chroot.so",
]

[[FileDigestGroup]]
package = "pam_snapper"
type = "pam"
note = "legacy: not audited"
bug = "bnc#815383"
nodigests = [
    "*/security/pam_snapper.so",
]

[[FileDigestGroup]]
package = "gdm"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1004346"
nodigests = [
    "*/security/pam_gdm.so",
]

[[FileDigestGroup]]
package = "slurm-pam_slurm"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1007053, bsc#1116758"
nodigests = [
    "*/security/pam_slurm.so",
    "*/security/pam_slurm_adopt.so",
]

[[FileDigestGroup]]
package = "pam_script"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1039848"
nodigests = [
    "*/security/pam_script.so",
]

[[FileDigestGroup]]
package = "pam_yubico"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1087060"
nodigests = [
    "*/security/pam_yubico.so",
]

[[FileDigestGroup]]
package = "pam_oath"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1089114"
nodigests = [
    "*/security/pam_oath.so",
]

[[FileDigestGroup]]
package = "pam_p11"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1123916"
nodigests = [
    "*/security/pam_p11.so",
]

[[FileDigestGroup]]
package = "pam_cifscreds"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1150527"
nodigests = [
    "*/security/pam_cifscreds.so",
]

[[FileDigestGroup]]
package = "pam_pwquality"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1150520"
nodigests = [
    "*/security/pam_pwquality.so",
]

[[FileDigestGroup]]
package = "pam_cgfs"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1150519"
nodigests = [
    "*/security/pam_cgfs.so",
]

[[FileDigestGroup]]
package = "google-authenticator-libpam"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1150524"
nodigests = [
    "*/security/pam_google_authenticator.so",
]

[[FileDigestGroup]]
package = "pam_u2f"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1087061"
nodigests = [
    "*/security/pam_u2f.so",
]

[[FileDigestGroup]]
package = "pam_kwallet"
type = "pam"
note = "legacy: not audited"
bug = "bsc#993806"
nodigests = [
    "*/security/pam_kwallet5.so",
]

[[FileDigestGroup]]
package = "pam_dbus"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1039709"
nodigests = [
    "*/security/pam_dbus.so",
]

[[FileDigestGroup]]
package = "google-guest-oslogin"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1146353"
nodigests = [
    "*/security/pam_oslogin_admin.so",
    "*/security/pam_oslogin_login.so",
]

[[FileDigestGroup]]
package = "fprintd-pam"
type = "pam"
note = "legacy: not audited"
bug = "bsc#792095"
nodigests = [
    "*/security/pam_fprintd.so",
]

[[FileDigestGroup]]
package = "mariadb"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1163362"
nodigests = [
    "*/security/pam_user_map.so",
]

[[FileDigestGroup]]
package = "oddjob-mkhomedir"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1169494"
nodigests = [
    "*/security/pam_oddjob_mkhomedir.so",
]

[[FileDigestGroup]]
package = "cockpit-ws"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1169614"
nodigests = [
    "*/security/pam_cockpit_cert.so",
    "*/security/pam_ssh_add.so",
]

[[FileDigestGroup]]
package = "kanidm-unixd-clients"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1173387"
nodigests = [
    "*/security/pam_kanidm.so",
]

[[FileDigestGroup]]
package = "malcontent"
type = "pam"
note = "legacy: not audited"
bug = "bsc#1177974"
nodigests = [
    "*/security/pam_malcontent.so",
]

[[FileDigestGroup]]
package = "sssd"
type = "pam"
note = "sssd gssapi extension"
bug = "bsc#1182509"
nodigests = [
    "*/security/pam_sss_gss.so",
]

[[FileDigestGroup]]
package = "oddjob-gpupdate"
type = "pam"
note = "samba group-policy update helper"
bug = "bsc#1188680"
nodigests = [
    "*/security/pam_oddjob_gpupdate.so",
]
