PieExecutables = [
    "/bin/ping",
    "/usr/bin/ping",
    "/bin/ping6",
    "/usr/bin/ping6",
    "/bin/su",
    "/usr/bin/su",
    "/usr/bin/pidgin",
    "/sbin/arping",
    "/sbin/clockdiff",
    "/sbin/dhclient",
    "/sbin/dhcpcd",
    "/sbin/klogd",
    "/sbin/rpcbind",
    "/sbin/syslogd",
    "/sbin/tracepath",
    "/sbin/tracepath6",
    "/usr/bin/uniconv",
    "/usr/bin/achfile",
    "/usr/bin/adv1tov2",
    "/usr/bin/aecho",
    "/usr/bin/afile",
    "/usr/bin/afppasswd",
    "/usr/bin/at",
    "/usr/bin/cadaver",
    "/usr/bin/chage",
    "/usr/bin/chfn",
    "/usr/bin/chsh",
    "/usr/bin/ciptool",
    "/usr/bin/cnid_index",
    "/usr/bin/dig",
    "/usr/bin/dund",
    "/usr/bin/expiry",
    "/usr/bin/finger",
    "/usr/bin/getzones",
    "/usr/bin/gpasswd",
    "/usr/bin/gpg",
    "/usr/bin/gpgsplit",
    "/usr/bin/gpgv",
    "/usr/bin/hcitool",
    "/usr/bin/hidd",
    "/usr/bin/host",
    "/usr/bin/htpasswd",
    "/usr/bin/l2ping",
    "/usr/bin/lppasswd",
    "/usr/bin/megatron",
    "/usr/bin/nbplkup",
    "/usr/bin/nbprgstr",
    "/usr/bin/nbpunrgstr",
    "/usr/bin/ncplogin",
    "/usr/bin/ncpmap",
    "/usr/bin/net",
    "/usr/bin/newgrp",
    "/usr/bin/nmblookup",
    "/usr/bin/nslookup",
    "/usr/bin/nsupdate",
    "/usr/bin/nwsfind",
    "/usr/bin/omshell",
    "/usr/bin/pand",
    "/usr/bin/pap",
    "/usr/bin/papstatus",
    "/usr/bin/passwd",
    "/usr/bin/pdbedit",
    "/usr/bin/profiles",
    "/usr/bin/psorder",
    "/usr/bin/rcp",
    "/usr/bin/rexec",
    "/usr/bin/rfcomm",
    "/usr/bin/rlogin",
    "/usr/bin/rpcclient",
    "/usr/bin/rsh",
    "/usr/bin/scp",
    "/usr/bin/sdptool",
    "/usr/bin/sftp",
    "/usr/bin/showppd",
    "/usr/bin/smbcacls",
    "/usr/bin/smbclient",
    "/usr/bin/smbcontrol",
    "/usr/bin/smbcquotas",
    "/sbin/mount.cifs",
    "/usr/bin/smbpasswd",
    "/usr/bin/smbspool",
    "/usr/bin/smbstatus",
    "/usr/bin/smbtree",
    "/usr/bin/ssh",
    "/usr/bin/ssh-add",
    "/usr/bin/ssh-agent",
    "/usr/bin/ssh-keygen",
    "/usr/bin/ssh-keyscan",
    "/usr/bin/svn",
    "/usr/bin/svnadmin",
    "/usr/bin/svndumpfilter",
    "/usr/bin/svnlook",
    "/usr/bin/svnserve",
    "/usr/bin/svnversion",
    "/usr/bin/talk",
    "/usr/bin/telnet",
    "/usr/bin/testparm",
    "/usr/bin/testprns",
    "/usr/bin/timeout",
    "/usr/bin/wbinfo",
    "/usr/lib/mit/bin/ftp",
    "/usr/lib/mit/bin/gss-client",
    "/usr/lib/mit/bin/kdestroy",
    "/usr/lib/mit/bin/kinit",
    "/usr/lib/mit/bin/klist",
    "/usr/lib/mit/bin/kpasswd",
    "/usr/lib/mit/bin/krb524init",
    "/usr/lib/mit/bin/ksu",
    "/usr/lib/mit/bin/kvno",
    "/usr/lib/mit/bin/rcp",
    "/usr/lib/mit/bin/rlogin",
    "/usr/lib/mit/bin/rsh",
    "/usr/lib/mit/bin/sclient",
    "/usr/lib/mit/bin/sim_client",
    "/usr/lib/mit/bin/telnet",
    "/usr/lib/mit/bin/uuclient",
    "/usr/lib/mit/bin/v4rcp",
    "/usr/lib/mit/sbin/ftpd",
    "/usr/lib/mit/sbin/gss-server",
    "/usr/lib/mit/sbin/kadmin",
    "/usr/lib/mit/sbin/kadmin.local",
    "/usr/lib/mit/sbin/kadmind",
    "/usr/lib/mit/sbin/kdb5_util",
    "/usr/lib/mit/sbin/klogind",
    "/usr/lib/mit/sbin/kprop",
    "/usr/lib/mit/sbin/kpropd",
    "/usr/lib/mit/sbin/krb524d",
    "/usr/lib/mit/sbin/krb5kdc",
    "/usr/lib/mit/sbin/kshd",
    "/usr/lib/mit/sbin/ktutil",
    "/usr/lib/mit/sbin/login.krb5",
    "/usr/lib/mit/sbin/sim_server",
    "/usr/lib/mit/sbin/sserver",
    "/usr/lib/mit/sbin/telnetd",
    "/usr/lib/mit/sbin/uuserver",
    "/usr/lib/news/bin/innd",
    "/usr/lib/news/bin/innbind",
    "/usr/lib/news/bin/rnews",
    "/usr/sbin/afpd",
    "/usr/sbin/amcheck",
    "/usr/sbin/amdd",
    "/usr/sbin/atalkd",
    "/usr/sbin/atd",
    "/usr/sbin/automount",
    "/usr/sbin/chat",
    "/usr/sbin/cnid_dbd",
    "/usr/sbin/cnid_metad",
    "/usr/sbin/cron",
    "/usr/sbin/cupsd",
    "/usr/sbin/dhcpd",
    "/usr/sbin/dhcrelay",
    "/usr/sbin/dnssec-keygen",
    "/usr/sbin/dnssec-signzone",
    "/usr/sbin/exim",
    "/usr/sbin/hciattach",
    "/usr/sbin/bluetoothd",
    "/usr/sbin/hciconfig",
    "/usr/sbin/hid2hci",
    "/usr/sbin/httpd2",
    "/usr/sbin/httpd2-prefork",
    "/usr/sbin/httpd2-worker",
    "/usr/sbin/in.fingerd",
    "/usr/sbin/in.ntalkd",
    "/usr/sbin/in.rexecd",
    "/usr/sbin/in.rlogind",
    "/usr/sbin/in.rshd",
    "/usr/sbin/in.telnetd",
    "/usr/sbin/irqbalance",
    "/usr/sbin/lwresd",
    "/usr/sbin/mailstats",
    "/usr/sbin/makemap",
    "/usr/sbin/named",
    "/usr/sbin/named-checkconf",
    "/usr/sbin/named-checkzone",
    "/usr/sbin/nmbd",
    "/usr/sbin/nscd",
    "/usr/sbin/ntlm_auth",
    "/usr/sbin/ntp-keygen",
    "/usr/sbin/ntpd",
    "/usr/sbin/ntpdc",
    "/usr/sbin/ntpq",
    "/usr/sbin/ntptime",
    "/usr/sbin/openvpn",
    "/usr/sbin/papd",
    "/usr/sbin/postfix",
    "/usr/sbin/pppd",
    "/usr/sbin/praliases",
    "/usr/sbin/radiusd",
    "/usr/sbin/rarpd",
    "/usr/sbin/rndc",
    "/usr/sbin/rndc-confgen",
    "/usr/sbin/rotatelogs2",
    "/usr/sbin/rpc.mountd",
    "/usr/sbin/rpc.nfsd",
    "/usr/sbin/rpc.rquotad",
    "/usr/sbin/rpc.rwalld",
    "/usr/sbin/rpc.yppasswdd",
    "/usr/sbin/rpc.ypxfrd",
    "/usr/sbin/safe_finger",
    "/usr/sbin/sendmail",
    "/usr/lib/sudo/sesh",
    "/usr/lib/openldap/slapd",
    "/usr/sbin/smartctl",
    "/usr/sbin/smartd",
    "/usr/sbin/smbd",
    "/usr/sbin/snmpd",
    "/usr/sbin/snmptrapd",
    "/usr/sbin/squid",
    "/usr/sbin/squidclient",
    "/usr/sbin/sshd",
    "/usr/sbin/stunnel",
    "/usr/sbin/suexec2",
    "/usr/sbin/tcpd",
    "/usr/sbin/tickadj",
    "/usr/sbin/traceroute",
    "/usr/sbin/traceroute6",
    "/usr/sbin/try-from",
    "/usr/sbin/utempter",
    "/usr/sbin/visudo",
    "/usr/sbin/vsftpd",
    "/usr/sbin/winbindd",
    "/usr/sbin/xinetd",
    "/usr/sbin/yppush",
    "/usr/sbin/ypserv",
    "/usr/bin/zone2ldap",
]
