[Scoring]
cron-file-digest-mismatch = 10000
cron-file-ghost = 10000
cron-file-unauthorized = 10000
cron-file-symlink = 10000
dbus-file-digest-mismatch = 10000
dbus-file-ghost = 10000
dbus-file-parse-error = 10000
dbus-file-unauthorized = 10000
dbus-file-symlink = 10000
dbus-policy-allow-wildcard = 10000
device-mismatched-attrs = 10000
device-unauthorized-file = 10000
invalid-license = 100000
pam-file-ghost = 10000
pam-file-unauthorized = 10000
pam-file-symlink = 10000
permissions-directory-setuid-bit = 10000
permissions-file-digest-mismatch = 10000
permissions-file-ghost = 10000
permissions-file-unauthorized = 10000
permissions-file-setuid-bit = 10000
permissions-file-symlink = 10000
# this one is problematic, because e.g. /etc/cron.* is packaged by multiple
# packages and only one should be responsible for caring about %postin
permissions-missing-postin = 100
permissions-parse-error = 10000
polkit-file-digest-mismatch = 10000
polkit-file-ghost = 10000
polkit-file-unauthorized = 10000
polkit-file-symlink = 10000
polkit-ghost-file = 10000
polkit-untracked-privilege = 10000
polkit-user-privilege = 10000
polkit-xml-exception = 10000
sudoers-file-digest-mismatch = 10000
sudoers-file-ghost = 10000
sudoers-file-unauthorized = 10000
sudoers-file-symlink = 10000
sysctl-file-digest-mismatch = 10000
sysctl-file-ghost = 10000
sysctl-file-unauthorized = 10000
sysctl-file-symlink = 10000
systemd-tmpfile-entry-unauthorized = 10000
systemd-tmpfile-ghost = 10000
systemd-tmpfile-parse-error = 10000
systemd-tmpfile-symlink = 10000
world-writable-mismatched-attrs = 10000
world-writable-unauthorized-file = 10000
zypperplugin-file-digest-mismatch = 10000
zypperplugin-file-ghost = 10000
zypperplugin-file-unauthorized = 10000
