[[FileDigestGroup]]
package = "rpmlint-integration-test"
type = "sudoers"
note = "valid test whitelisting entry for the OBS integration test package"
bug = "bsc#1188704"
[[FileDigestGroup.digests]]
path = "/etc/sudoers.d/valid-but-evil-rules"
digester = "shell"
hash = "84cf85013ddd404fd1f67ccf1259567b573057cd3b5bfa2696cf9f25c25dfcab"

[[FileDigestGroup]]
package = "rpmlint-integration-test"
type = "sudoers"
note = "mismatching test whitelisting entry for the OBS integration test package"
bug = "bsc#1188704"
[[FileDigestGroup.digests]]
path = "/etc/sudoers.d/mismatching-rules"
digester = "shell"
hash = "a4cf85013ddd404ad1f67ccf1259567b57305acd3b5bfaa696cf9f25a25dfcaa"

[[FileDigestGroup]]
package = "monitoring-plugins-smart"
type = "sudoers"
note = "Nagios plugin for monitoring SMART device status. Rather complex Perl script"
bugs = ["bsc#1196138", "bsc#1211003"]
[[FileDigestGroup.digests]]
path = "/etc/sudoers.d/monitoring-plugins-smart"
digester = "shell"
hash = "33f31f541d7c2cc42ba513d4b062019cf79569a7ea1b3b58e875c4edce413a25"

[[FileDigestGroup]]
package = "monitoring-plugins-zypper"
type = "sudoers"
note = "Nagios plugin for monitoring zypper update list. A couple of read-only zypper sub-commands"
bug = "bsc#1196139"
[[FileDigestGroup.digests]]
path = "/etc/sudoers.d/check_zypper"
digester = "shell"
hash = "7c28565571a13de93e79753e7c8ce6c0c7fd6fc5a2df8ba7c760ecc17004947a"

[[FileDigestGroup]]
package = "cscreen"
type = "sudoers"
note = "Allows members of the _cscreen group to attach to a shared screen session"
bug = "bsc#1196140"
[[FileDigestGroup.digests]]
path = "/etc/sudoers.d/cscreen"
digester = "shell"
hash = "f031ed532175450fa1352ab924130970509e9c742c95277a90f5d0da6c5f0f87"

[[FileDigestGroup]]
package = "leafnode"
type = "sudoers"
note = "Allows members of the newsadmin group to fetch news"
bug = "bsc#1196142"
[[FileDigestGroup.digests]]
path = "/etc/sudoers.d/leafnode"
digester = "shell"
hash = "88d39bcbdba7c9485ab5f73617b8d9763385aa8e9f598e808dd025fba0d8d445"

[[FileDigestGroup]]
package = "ceph-base"
type = "sudoers"
note = "allows to run smartctl and nvme programs to collect device health metrics"
bug = "bsc#1196141"
[[FileDigestGroup.digests]]
path = "/etc/sudoers.d/ceph-smartctl"
digester = "shell"
hash = "bdb2f32eb3285679a23b428303a3529b7d35978e7f29bcd93d711034953f2429"

[[FileDigestGroup]]
package = "gnome-branding-Aeon"
type = "sudoers"
note = "allow wheel group members to run commands as root by entering their own password"
bug = "bsc#1215276"
[[FileDigestGroup.digests]]
path = "/usr/etc/sudoers.d/50-aeon"
digester = "shell"
hash = "554ad7ffea09c0c9bed71f6ef7621e729d9d5368175b6e3b0e29214531d14c39"

[[FileDigestGroup]]
package = "plasma-branding-Kalpa"
type = "sudoers"
note = "allow wheel group members to run commands as root by entering their own password"
bug = "bsc#1217706"
[[FileDigestGroup.digests]]
path = "/usr/etc/sudoers.d/50-kalpa"
digester = "shell"
hash = "554ad7ffea09c0c9bed71f6ef7621e729d9d5368175b6e3b0e29214531d14c39"

[[FileDigestGroup]]
package = "sudo-policy-sudo-auth-self"
type = "sudoers"
note = "allow members of the sudo group to authenticate using their own passowrd"
bug = "bsc#1257092"
[[FileDigestGroup.digests]]
path = "/usr/etc/sudoers.d/50-sudo-auth-self"
digester = "shell"
hash = "6871f243bc26ac29e1b283f30e3e58d327c0da4670ecff6591738849a5b59877"

[[FileDigestGroup]]
package = "sudo-policy-wheel-auth-self"
type = "sudoers"
note = "allow members of the wheel group to authenticate using their own passowrd"
bug = "bsc#1257092"
[[FileDigestGroup.digests]]
path = "/usr/etc/sudoers.d/50-wheel-auth-self"
digester = "shell"
hash = "554ad7ffea09c0c9bed71f6ef7621e729d9d5368175b6e3b0e29214531d14c39"

[[FileDigestGroup]]
package = "servicetray"
type = "sudoers"
note = "allow members of the users group to invoke servicetray_systemctl"
bug = "bsc#1257103"
[[FileDigestGroup.digests]]
path = "/usr/etc/sudoers.d/servicetray"
digester = "shell"
hash = "e6991727d5b08bf3f4425e88336d3f948ca0bc7ecf018f25b850c72d8f9a6638"
