StandardGroups = [
    'aegis',
    'antivir',
    'arangodb',
    'at',
    'audio',
    'avahi',
    'bacula',
    'beagleindex',
    'bigsister',
    'bin',
    'bird',
    'bitcoin',
    'bitlbee',
    'boinc',
    'casaauth',
    'cdrom',
    'ceilometer',
    'ceph',
    'cephadm',
    'chef',
    'chrony',
    'cinder',
    'citadel',
    'colord',
    'conman',
    'console',
    'coroqnetd',
    'coturn',
    'crowbar',
    'cwbconv',
    '_cscreen',
    'daapd',
    'daemon',
    'davfs2',
    'dba',
    'ddclient',
    'dehydrated',
    'dialout',
    'disk',
    'distcc',
    'dnscrypt',
    'dosemu',
    'dovecot',
    'elasticsearch',
    'epmd',
    'festival',
    'ffums',
    'firebird',
    'firejail',
    'floppy',
    'fonehome',
    'ftp',
    'games',
    'gdm',
    'gerbera',
    'geronimo',
    'glance',
    '_gns3',
    'grafana',
    'guixbuild',
    'haclient',
    'haldaemon',
    'heat',
    'hsqldb',
    'icecast',
    'icecream',
    'icinga',
    'icingacmd',
    'ifdrwww',
    'intermezzo',
    'iouyap',
    'jboss',
    'jenkins',
    'jetty5',
    'jitsi',
    'jonas',
    'keystone',
    'kmem',
    'kolab',
    'kolab-n',
    'kolab-r',
    'kvm',
    'ldap',
    'libstoragemgmt',
    'libvirt',
    'lightdm',
    'lighttpd',
    'localham',
    'locate',
    'logstash',
    'lp',
    'lxdm',
    'mail',
    'maildrop',
    'mailman',
    'man',
    'mdom',
    'memcached',
    'messagebus',
    'minetest',
    'mktex',
    'modem',
    'mumble-server',
    'munge',
    'mysql',
    'nagcmd',
    'nagios',
    'named',
    'neutron',
    'news',
    'nginx',
    'nobody',
    'nogroup',
    'nova',
    'novell_nogroup',
    'novlxtier',
    '_nsd',
    'ntadmin',
    'ntop',
    'ntp',
    'oinstall',
    'openvswitch',
    'orthanc',
    'otrs',
    'ovirtagent',
    'pcp',
    'pcpqa',
    'pdns',
    'pegasus',
    'pkcs11',
    'polipo',
    'polkituser',
    'postfix',
    'postgres',
    'pound',
    'powersave',
    'privoxy',
    'prometheus',
    'prosody',
    'ptokax',
    'public',
    'pulse',
    'pulse-access',
    'pulse-rt',
    'puppet',
    'qemu',
    'quagga',
    'quasselcore',
    'rabbitmq',
    'radicale',
    'radiusd',
    'root',
    'sabayon-admin',
    'salt',
    'sanlock',
    'sapdb',
    'sddm',
    'sensu',
    'shadow',
    'shibd',
    'singularity',
    'siproxd',
    '_sks',
    'slurm',
    'snort',
    'sogo',
    'squid',
    'sshd',
    'suse-ncc',
    'svn',
    'swift',
    'synapse',
    'sys',
    'systemd-journal',
    'systemd-journal-gateway',
    'tape',
    'tftp',
    'tomcat',
    'tomcat4',
    'tor',
    'tox',
    'trove',
    'trusted',
    'tryton',
    'tss',
    'ts-shell',
    'tty',
    'unbound',
    'users',
    'utmp',
    'uucp',
    'uuidd',
    'vacation',
    'varnish',
    'video',
    'vnc',
    'vscan',
    'warewulf',
    'wheel',
    'wireshark',
    'www',
    'xok',
    'xrootd',
    'xymon',
    'zabbix',
    'zabbixs',
    'zeroinst',
    'zkeyadm',
    'znc',
    'zope',
]

StandardUsers = [
    'aegis',
    'amanda',
    'aodh',
    'arangodb',
    'asterisk',
    'at',
    'avahi',
    'bacula',
    'barbican',
    'beagleindex',
    'bigsister',
    'bin',
    'bird',
    'bitcoin',
    'bitlbee',
    'boinc',
    'casaatsd',
    'casaatvd',
    'casaauth',
    'ceilometer',
    'ceph',
    'cephadm',
    'chef',
    'chrony',
    'cinder',
    'citadel',
    'cntlm',
    'colord',
    'conman',
    'cop',
    'coroqnetd',
    'coturn',
    'crowbar',
    'cyrus',
    '_cscreen',
    'daapd',
    'daemon',
    'davfs2',
    'ddclient',
    'dehydrated',
    'designate',
    'dhcpd',
    'distcc',
    'dnscrypt',
    'dovecot',
    'dpbox',
    'dvbdaemon',
    'ec2-api',
    'elasticsearch',
    'epmd',
    'fax',
    'festival',
    'fetchmail',
    'ffums',
    'firebird',
    'fonehome',
    'ftp',
    'games',
    'gdm',
    'gerbera',
    'geronimo',
    'glance',
    'gnats',
    'gnocchi',
    '_gns3',
    'gnump3d',
    'grafana',
    'hacluster',
    'haldaemon',
    'heat',
    'hsqldb',
    'icecast',
    'icecream',
    'icinga',
    'intermezzo',
    'iodined',
    'irc',
    'ironic',
    'jabber',
    'jboss',
    'jenkins',
    'jetty5',
    'jibri',
    'jicofo',
    'jonas',
    'jvb',
    'keystone',
    'kolab',
    'kolab-n',
    'kolab-r',
    'ldap',
    'libstoragemgmt',
    'lightdm',
    'lighttpd',
    'logstash',
    'lp',
    'lxdm',
    'magnum',
    'mail',
    'mailman',
    'man',
    'manila',
    'mdnsd',
    'mdom',
    'mednafen',
    'memcached',
    'messagebus',
    'minetest',
    'mktex',
    'mpd',
    'mumble-server',
    'munge',
    'murano',
    'mysql',
    'nagios',
    'named',
    'neutron',
    'news',
    'nginx',
    'nova',
    'novell_nobody',
    'novlifdr',
    'novlxregd',
    'novlxsrvd',
    '_nsd',
    'ntop',
    'ntp',
    'octavia',
    'openvswitch',
    'oracle',
    'orthanc',
    'otrs',
    'ovirtagent',
    'partimag',
    'pcp',
    'pcpqa',
    'pdns',
    'pegasus',
    'polipo',
    'polkitd',
    'polkituser',
    'pop',
    'postfix',
    'postgres',
    'postgrey',
    'pound',
    'privoxy',
    'prometheus',
    'prosody',
    'ptokax',
    'pulse',
    'puppet',
    'qemu',
    'quagga',
    'quasselcore',
    'rabbitmq',
    'radicale',
    'radiusd',
    'radvd',
    '_rmt',
    'root',
    'sabayon-admin',
    'sahara',
    'salt',
    'sanlock',
    'sapdb',
    'sddm',
    'sensu',
    'shibd',
    'siproxd',
    '_sks',
    'slurm',
    'snort',
    'sogo',
    'squid',
    'sshd',
    'statd',
    'suse-ncc',
    'svn',
    'swift',
    'synapse',
    'systemd-journal-gateway',
    'tftp',
    'tomcat',
    'tomcat4',
    'tor',
    'toxcmd',
    'trove',
    'tryton',
    'tss',
    'ulogd',
    'unbound',
    'upsd',
    'uucp',
    'uuidd',
    'vacation',
    'varnish',
    'vdr',
    'vnc',
    'vscan',
    'wnn',
    'wwwrun',
    'xrootd',
    'xymon',
    'yastws',
    'zabbix',
    'zabbixs',
    'zaqar',
    'zeroinst',
    'znc',
    'zope',
]
